Repository CS342/2024-Prisma, pull requests merged in 2024-01, with the labels that each got.

#2 Fix Firebase Project ID
  .firebaserc
  Behavior/Supporting Files/GoogleService-Info.plist
Labels: bug

#7 Update README & CodeCov Setup
  README.md
  codecov.yml
Labels: documentation

#3 feature/task1-adjust-contacts
  Behavior.xcodeproj/project.pbxproj
  Behavior/Contacts/Contacts.swift
  Behavior/Resources/AppIcon.png
  Behavior/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Behavior/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Behavior/Resources/Localizable.xcstrings
Labels: enhancement

#6 Configure HealthKit and notification authorizations
  Behavior.xcodeproj/project.pbxproj
  Behavior.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Behavior/BehaviorDelegate.swift
  Behavior/Onboarding/NotificationPermissions.swift
  Behavior/Onboarding/OnboardingFlow.swift
  Behavior/Resources/Localizable.xcstrings
Labels: enhancement

#8 Editing Onboarding Text and Icons
  Behavior/Onboarding/InterestingModules.swift
  Behavior/Onboarding/Welcome.swift
  Behavior/Resources/Localizable.xcstrings
Labels: enhancement

#11 Fix Firebase Deployment
  .firebaserc
  Prisma/Supporting Files/GoogleService-Info.plist
Labels: enhancement
